### ISSUE TITLE
Incorrect typing of getLists return value

### ISSUE THREAD

**Issue by bjmiller** [mikerourke/trello-for-wolves#21]
Looking here:
https://github.com/mikerourke/trello-for-wolves/blob/a6c3014b5f3d03858a5fd8f714a7e0a984447b43/src/resources/List.ts#L33-L40

Isn't line 38 supposed to be `TypedFetch<ListRecord[]>` instead of `TypedFetch<LabelRecord[]>`?

It would help me a lot if this were fixed.

**Comment by mikerourke** [comment]
I'll take care of it first thing tomorrow morning. Sorry about that!

**Comment by mikerourke** [comment]
@bjmiller I just published v2.0.7 with the fix. Enjoy!

**Comment by bjmiller** [comment]
Thank you!  I just updated, and it looks like even though the source is correct, the .d.ts file in 2.0.7 still has the old value.  Maybe it didn't get replaced during the build?

**Comment by mikerourke** [comment]
Ah crap! I forgot to build before publishing! I just re-built and published a new version (v2.0.8) so it should have the new types in there now.

**Comment by bjmiller** [comment]
We're all good now.  Thank you again!
