### ISSUE TITLE
Authorization of users

### ISSUE THREAD

**Issue by gkruel** [mikerourke/trello-for-wolves#5]
Does trello-for-wolves provide a way for users to authorize my app with their trello account? The trello documentation states that I can use oAuth but I was wondering if your package already has this functionality. Thanks.

**Comment by mikerourke** [comment]
@gkruel I apologize for the delayed response. There currently isn't any OAuth functionality built in to the library. It might be out of the scope of the library. I think most people prefer to handle authentication with a separate dependency. I can do a more detailed evaluation of what it would take to implement this functionality as soon as the holidays are over. I'll keep you posted on my progress.

**Comment by gkruel** [comment]
Thanks for the response and happy holidays.


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Mike Rourke <notifications@github.com> Date: 12/26/17  4:04 PM  (GMT-07:00) To: mikerourke/trello-for-wolves <trello-for-wolves@noreply.github.com> Cc: gkruel <gkruel@me.com>, Mention <mention@noreply.github.com> Subject: Re: [mikerourke/trello-for-wolves] Authorization of users (#5) 
@gkruel I apologize for the delayed response. There currently isn't any OAuth functionality built in to the library. It might be out of the scope of the library. I think most people prefer to handle authentication with a separate dependency. I can do a more detailed evaluation of what it would take to implement this functionality as soon as the holidays are over. I'll keep you posted on my progress.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mikerourke/trello-for-wolves","title":"mikerourke/trello-for-wolves","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mikerourke/trello-for-wolves"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mikerourke in #5: @gkruel I apologize for the delayed response. There currently isn't any OAuth functionality built in to the library. It might be out of the scope of the library. I think most people prefer to handle authentication with a separate dependency. I can do a more detailed evaluation of what it would take to implement this functionality as soon as the holidays are over. I'll keep you posted on my progress."}],"action":{"name":"View Issue","url":"https://github.com/mikerourke/trello-for-wolves/issues/5#issuecomment-354022984"}}}
